FROM opensearchstaging/opensearch:3.2.0

# Install the OTel plugin.
# RUN /usr/share/opensearch/bin/opensearch-plugin install --batch https://artifacts.opensearch.org/snapshots/plugins/telemetry-otel/3.2.0/telemetry-otel-3.2.0.zip
