FROM opensearchproject/opensearch:2.15.0

# Install the opensearch-ubi plugin.
RUN /usr/share/opensearch/bin/opensearch-plugin install --batch https://github.com/opensearch-project/user-behavior-insights/releases/download/2.15.0.0/opensearch-ubi-2.15.0.0.zip
