version: '3.7'
services:
  opensearch:
    container_name: opensearch
    build: ./opensearch/.
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
      http.cors.enabled: true
      # Warning: this is opening it up to all cross domains
      http.cors.allow-origin: "*"
      http.cors.allow-methods: OPTIONS,HEAD,GET,POST,PUT,DELETE
      http.cors.allow-credentials: true
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,test,access-control-allow-headers,x-search-query,X-Search-Id,X-Search-Filters,X-ubi-query-id,X-ubi-store,X-ubi-user-id,X-ubi-session-id,x-search-client,Access-Control-Expose-Headers
      # indexes faster if we don't log each row (i.e. logger.level: warn)
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: Mysupersecretpassword_123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD", "wget", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 50

  data-prepper:
    container_name: data-prepper
    build: ./data-prepper/.
    restart: unless-stopped
    #image: opensearchproject/data-prepper:2.7.0
    #volumes:
    #  - ../trace_analytics_no_ssl_2x.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
    #  - ../data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    #  - ../demo/root-ca.pem:/usr/share/data-prepper/root-ca.pem
    ports:
      - "8080:8080"
    #networks:
    #  - chorus-net
    depends_on:
      - opensearch
    #  - chorus_ui


