FROM  opensearchproject/opensearch-dashboards:3.5.0
#FROM opensearchstaging/opensearch-dashboards:3.5.0

COPY --chown=opensearch-dashboards:opensearch-dashboards opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/
