#FROM  opensearchproject/opensearch-dashboards:3.5.0
#FROM opensearchstaging/opensearch-dashboards:3.6.0
FROM dep4b/ericstuff:osd2

COPY --chown=opensearch-dashboards:opensearch-dashboards opensearch_dashboards.yml /usr/share/opensearch-dashboards/config/
