chorus-ubi-otel-pipeline:
  source:
    otel_trace_source:
      port: 21890
      ssl: false
  buffer:
    bounded_blocking:
      buffer_size: 150
      batch_size: 1
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        index_type: custom
        index: otel_ubi_events
        username: "admin"
        password: "MyStr0ng!P@ssw0rd2024"  
        insecure: true      
#    - stdout:
chorus-ubi-pipeline:
  source:
    http:
      port: 2021
      ssl: false
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        index_type: custom
        index: ubi_queries
        username: "admin"
        password: "MyStr0ng!P@ssw0rd2024"
        insecure: true
    - stdout:
