FROM opensearchproject/data-prepper:2.7.0
#EXPOSE 8080

COPY pipelines.yaml /usr/share/data-prepper/pipelines/pipelines.yaml
COPY data-prepper-config.yaml /usr/share/data-prepper/config/data-prepper-config.yaml


